// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thyzkqqfkgxudynxfpay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoeXprcXFma2d4dWR5bnhmcGF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTc4NjMsImV4cCI6MjA2NTU5Mzg2M30.l1CmnxnEVu4CkMQNQUhhkiyb2kCVXXVSFuIe99FAoFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);